baseURL = 'http://seblw.me'
languageCode = 'en-us'
title = "seblw's blog"
theme = "nostyleplease"

[params]
  [params.theme_config]
    back_home_text = ".."
    date_format = "2006-01-02"


[markup]
  [markup.highlight]
